# -*- coding: utf-8 -*-
import json
import urllib.request
import urllib.error
import time
import sys

# Core 700 Academic/IELTS vocabulary words to query
ACADEMIC_WORDS = [
    # Band 0.0-4.0 (Foundation / B1)
    ("abandon", "từ bỏ, ruồng bỏ", "0.0-4.0", "General", "verb"),
    ("abstract", "trừu tượng", "0.0-4.0", "Education", "adjective"),
    ("access", "truy cập, lối vào", "0.0-4.0", "Technology", "noun"),
    ("accommodate", "đáp ứng, cung cấp chỗ ở", "0.0-4.0", "Society", "verb"),
    ("accompany", "đồng hành, đi cùng", "0.0-4.0", "Society", "verb"),
    ("accumulate", "tích lũy, gom góp", "0.0-4.0", "General", "verb"),
    ("accurate", "chính xác", "0.0-4.0", "Education", "adjective"),
    ("achieve", "đạt được, giành được", "0.0-4.0", "Work & Career", "verb"),
    ("acknowledge", "thừa nhận, công nhận", "0.0-4.0", "General", "verb"),
    ("acquire", "thu được, đạt được", "0.0-4.0", "Education", "verb"),
    ("adapt", "thích nghi, phỏng theo", "0.0-4.0", "Environment", "verb"),
    ("adequate", "đầy đủ, thỏa đáng", "0.0-4.0", "General", "adjective"),
    ("adjacent", "kề bên, sát vách", "0.0-4.0", "Urbanization", "adjective"),
    ("adjust", "điều chỉnh, dàn xếp", "0.0-4.0", "General", "verb"),
    ("administrate", "quản lý, hành chính", "0.0-4.0", "Work & Career", "verb"),
    ("adult", "người lớn, trưởng thành", "0.0-4.0", "Society", "noun"),
    ("advocate", "ủng hộ, tán thành", "0.0-4.0", "Society", "verb"),
    ("affect", "ảnh hưởng, tác động", "0.0-4.0", "General", "verb"),
    ("aggregate", "tổng hợp, gộp lại", "0.0-4.0", "General", "verb"),
    ("aid", "sự trợ giúp, viện trợ", "0.0-4.0", "Society", "noun"),
    ("albeit", "mặc dù, dẫu cho", "0.0-4.0", "General", "conjunction"),
    ("allocate", "phân bổ, phân phát", "0.0-4.0", "Work & Career", "verb"),
    ("alter", "thay đổi, biến đổi", "0.0-4.0", "General", "verb"),
    ("alternative", "lựa chọn thay thế", "0.0-4.0", "General", "noun"),
    ("ambiguous", "mơ hồ, nước đôi", "0.0-4.0", "Education", "adjective"),
    ("amend", "sửa đổi, bổ sung (luật)", "0.0-4.0", "Crime", "verb"),
    ("analogy", "sự tương tự, phép loại suy", "0.0-4.0", "Education", "noun"),
    ("analyse", "phân tích", "0.0-4.0", "Education", "verb"),
    ("analysis", "sự phân tích", "0.0-4.0", "Education", "noun"),
    ("annual", "hàng năm", "0.0-4.0", "General", "adjective"),
    ("anticipate", "lường trước, mong đợi", "0.0-4.0", "General", "verb"),
    ("apparent", "rõ ràng, bề ngoài", "0.0-4.0", "General", "adjective"),
    ("append", "đính kèm, viết thêm vào", "0.0-4.0", "Technology", "verb"),
    ("appreciate", "đánh giá cao, trân trọng", "0.0-4.0", "Society", "verb"),
    ("approach", "tiếp cận, phương pháp", "0.0-4.0", "General", "noun"),
    ("appropriate", "thích hợp, phù hợp", "0.0-4.0", "General", "adjective"),
    ("approximate", "xấp xỉ, gần đúng", "0.0-4.0", "General", "adjective"),
    ("arbitrary", "tùy ý, độc đoán", "0.0-4.0", "General", "adjective"),
    ("area", "khu vực, lĩnh vực", "0.0-4.0", "Urbanization", "noun"),
    ("aspect", "khía cạnh, diện mạo", "0.0-4.0", "General", "noun"),
    ("assemble", "lắp ráp, tụ họp", "0.0-4.0", "Technology", "verb"),
    ("assess", "đánh giá, định giá", "0.0-4.0", "Education", "verb"),
    ("assign", "phân công, bổ nhiệm", "0.0-4.0", "Work & Career", "verb"),
    ("assist", "giúp đỡ, trợ lý", "0.0-4.0", "Work & Career", "verb"),
    ("assume", "giả định, cho là", "0.0-4.0", "General", "verb"),
    ("assure", "cam đoan, bảo đảm", "0.0-4.0", "Work & Career", "verb"),
    ("attach", "đính kèm, gắn bó", "0.0-4.0", "Technology", "verb"),
    ("attain", "đạt được, giành được", "0.0-4.0", "Work & Career", "verb"),
    ("attitude", "thái độ", "0.0-4.0", "Society", "noun"),
    ("attribute", "thuộc tính, đặc tính", "0.0-4.0", "General", "noun"),
    ("author", "tác giả", "0.0-4.0", "Education", "noun"),
    ("authority", "quyền lực, chính quyền", "0.0-4.0", "Society", "noun"),
    ("automate", "tự động hóa", "0.0-4.0", "Technology", "verb"),
    ("available", "có sẵn, rảnh rỗi", "0.0-4.0", "General", "adjective"),
    ("aware", "nhận thức, biết rõ", "0.0-4.0", "Society", "adjective"),
    ("behalf", "thay mặt, nhân danh", "0.0-4.0", "Society", "noun"),
    ("benefit", "lợi ích", "0.0-4.0", "Health", "noun"),
    ("bias", "sự thiên vị, thành kiến", "0.0-4.0", "Society", "noun"),
    ("bond", "sự gắn kết, trái phiếu", "0.0-4.0", "Society", "noun"),
    ("brief", "ngắn gọn, vắn tắt", "0.0-4.0", "General", "adjective"),
    ("bulk", "phần lớn, số lượng lớn", "0.0-4.0", "General", "noun"),
    ("capable", "có khả năng, năng lực", "0.0-4.0", "Work & Career", "adjective"),
    ("capacity", "sức chứa, năng lực", "0.0-4.0", "General", "noun"),
    ("category", "thể loại, danh mục", "0.0-4.0", "General", "noun"),
    ("cease", "ngừng, chấm dứt", "0.0-4.0", "General", "verb"),
    ("challenge", "thử thách", "0.0-4.0", "Work & Career", "noun"),
    ("channel", "kênh truyền hình, luồng", "0.0-4.0", "Technology", "noun"),
    ("chapter", "chương (sách)", "0.0-4.0", "Education", "noun"),
    ("chart", "biểu đồ", "0.0-4.0", "Education", "noun"),
    ("chemical", "hóa chất, thuộc hóa học", "0.0-4.0", "Environment", "noun"),
    ("circumstance", "hoàn cảnh, tình huống", "0.0-4.0", "Society", "noun"),
    ("cite", "trích dẫn", "0.0-4.0", "Education", "verb"),
    ("civil", "thuộc dân sự, lịch sự", "0.0-4.0", "Society", "adjective"),
    ("clarify", "làm rõ, làm sáng tỏ", "0.0-4.0", "Education", "verb"),
    ("classic", "kinh điển, cổ điển", "0.0-4.0", "Education", "adjective"),
    ("clause", "điều khoản, mệnh đề", "0.0-4.0", "Crime", "noun"),
    ("code", "mã, quy tắc", "0.0-4.0", "Technology", "noun"),
    ("coherent", "chặt chẽ, mạch lạc", "0.0-4.0", "Education", "adjective"),
    ("coincide", "trùng hợp, xảy ra đồng thời", "0.0-4.0", "General", "verb"),
    ("collapse", "sụp đổ, đổ sập", "0.0-4.0", "Urbanization", "verb"),
    ("colleague", "đồng nghiệp", "0.0-4.0", "Work & Career", "noun"),
    ("commence", "bắt đầu, khởi đầu", "0.0-4.0", "Work & Career", "verb"),
    ("comment", "bình luận, nhận xét", "0.0-4.0", "Society", "noun"),
    ("commission", "ủy ban, tiền hoa hồng", "0.0-4.0", "Society", "noun"),
    ("commit", "cam kết, phạm tội", "0.0-4.0", "Crime", "verb"),
    ("commodity", "hàng hóa", "0.0-4.0", "Work & Career", "noun"),
    ("communicate", "giao tiếp, truyền đạt", "0.0-4.0", "Society", "verb"),
    ("community", "cộng đồng", "0.0-4.0", "Society", "noun"),
    ("compatible", "tương thích, hợp nhau", "0.0-4.0", "Technology", "adjective"),
    ("compensate", "đền bù, bồi thường", "0.0-4.0", "Work & Career", "verb"),
    ("compile", "biên soạn, thu thập", "0.0-4.0", "Education", "verb"),
    ("complement", "bổ sung, phần bù", "0.0-4.0", "General", "verb"),
    ("complex", "phức tạp", "0.0-4.0", "General", "adjective"),
    ("component", "thành phần, linh kiện", "0.0-4.0", "Technology", "noun"),
    ("compound", "hợp chất, phức hợp", "0.0-4.0", "Environment", "noun"),
    ("comprehensive", "toàn diện, bao quát", "0.0-4.0", "Education", "adjective"),
    ("comprise", "bao gồm, gồm có", "0.0-4.0", "General", "verb"),
    ("compute", "tính toán (bằng máy)", "0.0-4.0", "Technology", "verb"),
    ("conceive", "nhận thức, thụ thai", "0.0-4.0", "General", "verb"),
    ("concentrate", "tập trung", "0.0-4.0", "Education", "verb"),
    ("concept", "khái niệm", "0.0-4.0", "Education", "noun"),
    ("conclude", "kết luận", "0.0-4.0", "Education", "verb"),
    ("concurrent", "đồng thời, đồng quy", "0.0-4.0", "General", "adjective"),
    ("conduct", "tiến hành, chỉ dẫn", "0.0-4.0", "Education", "verb"),
    ("confer", "bàn bạc, phong tặng", "0.0-4.0", "Work & Career", "verb"),
    ("confine", "hạn chế, giam giữ", "0.0-4.0", "Crime", "verb"),
    ("confirm", "xác nhận, chứng thực", "0.0-4.0", "General", "verb"),
    ("conflict", "mâu thuẫn, xung đột", "0.0-4.0", "Society", "noun"),
    ("conform", "tuân thủ, phù hợp", "0.0-4.0", "Society", "verb"),
    ("consent", "sự đồng ý, bằng lòng", "0.0-4.0", "Crime", "noun"),
    ("consequent", "hậu quả, kết quả", "0.0-4.0", "General", "adjective"),
    ("considerable", "đáng kể, to lớn", "0.0-4.0", "General", "adjective"),
    ("consist", "bao gồm, gồm có", "0.0-4.0", "General", "verb"),
    ("constitute", "cấu thành, thiết lập", "0.0-4.0", "General", "verb"),
    ("constrain", "bắt buộc, kìm hãm", "0.0-4.0", "General", "verb"),
    ("construct", "xây dựng", "0.0-4.0", "Urbanization", "verb"),
    ("consult", "tham khảo, tư vấn", "0.0-4.0", "Health", "verb"),
    ("consume", "tiêu thụ, ăn uống", "0.0-4.0", "Environment", "verb"),
    ("contact", "liên lạc, tiếp xúc", "0.0-4.0", "Society", "noun"),
    ("contemporary", "đương đại, cùng thời", "0.0-4.0", "Society", "adjective"),
    ("context", "ngữ cảnh, bối cảnh", "0.0-4.0", "Education", "noun"),
    ("contract", "hợp đồng", "0.0-4.0", "Work & Career", "noun"),
    ("contradict", "mâu thuẫn, phủ nhận", "0.0-4.0", "General", "verb"),
    ("contrary", "trái ngược, ngược lại", "0.0-4.0", "General", "adjective"),
    ("contrast", "sự tương phản", "0.0-4.0", "General", "noun"),
    ("contribute", "đóng góp, góp phần", "0.0-4.0", "Society", "verb"),
    ("controversy", "sự tranh cãi", "0.0-4.0", "Society", "noun"),
    ("convene", "triệu tập, tụ họp", "0.0-4.0", "Society", "verb"),
    ("converse", "trò chuyện, ngược lại", "0.0-4.0", "Society", "verb"),
    ("convert", "chuyển đổi, biến đổi", "0.0-4.0", "Technology", "verb"),
    ("cooperate", "hợp tác, cộng tác", "0.0-4.0", "Society", "verb"),
    ("coordinate", "phối hợp, điều phối", "0.0-4.0", "Work & Career", "verb"),
    ("core", "cốt lõi, nhân", "0.0-4.0", "General", "noun"),
    ("corporate", "thuộc doanh nghiệp", "0.0-4.0", "Work & Career", "adjective"),
    ("correspond", "tương ứng, trao đổi thư từ", "0.0-4.0", "General", "verb"),
    ("create", "tạo ra, sáng tạo", "0.0-4.0", "Technology", "verb"),
    ("credit", "tín dụng, lòng tin", "0.0-4.0", "Work & Career", "noun"),
    ("criteria", "tiêu chí, chuẩn mực", "0.0-4.0", "Education", "noun"),
    ("crucial", "cốt yếu, tối quan trọng", "0.0-4.0", "General", "adjective"),
    ("culture", "văn hóa", "0.0-4.0", "Society", "noun"),
    ("currency", "tiền tệ", "0.0-4.0", "General", "noun"),
    ("cycle", "chu kỳ", "0.0-4.0", "Environment", "noun"),
    ("data", "dữ liệu", "0.0-4.0", "Technology", "noun"),
    ("debate", "tranh luận", "0.0-4.0", "Society", "noun"),
    ("decade", "thập kỷ", "0.0-4.0", "General", "noun"),
    ("decline", "suy giảm, từ chối", "0.0-4.0", "General", "verb"),
    ("deduct", "khấu trừ, trừ đi", "0.0-4.0", "Work & Career", "verb"),
    ("define", "định nghĩa", "0.0-4.0", "Education", "verb"),
    ("definite", "xác định, rõ ràng", "0.0-4.0", "General", "adjective"),
    ("demonstrate", "chứng minh, giải thích", "0.0-4.0", "Education", "verb"),
    ("denote", "biểu thị, chỉ rõ", "0.0-4.0", "Education", "verb"),
    ("deny", "phủ nhận, từ chối", "0.0-4.0", "Crime", "verb"),
    ("depress", "làm chán nản, suy thoái", "0.0-4.0", "Health", "verb"),
    ("deprive", "tước đoạt, lấy đi", "0.0-4.0", "Crime", "verb"),
    ("derive", "bắt nguồn từ, rút ra", "0.0-4.0", "General", "verb"),
    ("design", "thiết kế", "0.0-4.0", "Technology", "verb"),
    ("despite", "mặc dù, dẫu cho", "0.0-4.0", "General", "preposition"),
    ("detect", "phát hiện, dò tìm", "0.0-4.0", "Technology", "verb"),
    ("deviate", "lệch hướng, sai đường", "0.0-4.0", "General", "verb"),
    ("device", "thiết bị, công cụ", "0.0-4.0", "Technology", "noun"),
    ("devote", "cống hiến, dành cho", "0.0-4.0", "Society", "verb"),
    ("differentiate", "phân biệt", "0.0-4.0", "Education", "verb"),
    ("dimension", "kích thước, chiều", "0.0-4.0", "General", "noun"),
    ("diminish", "giảm bớt, thu nhỏ", "0.0-4.0", "General", "verb"),
    ("discrete", "riêng rẽ, rời rạc", "0.0-4.0", "General", "adjective"),
    ("discriminate", "phân biệt đối xử", "0.0-4.0", "Society", "verb"),
    ("displace", "thay thế, dời chỗ", "0.0-4.0", "Environment", "verb"),
    ("display", "hiển thị, trưng bày", "0.0-4.0", "Technology", "verb"),
    ("dispose", "sắp xếp, vứt bỏ", "0.0-4.0", "Environment", "verb"),
    ("distinction", "sự phân biệt, nét độc đáo", "0.0-4.0", "Education", "noun"),
    ("distort", "bóp méo, xuyên tạc", "0.0-4.0", "General", "verb"),
    ("distribute", "phân phối, phát hành", "0.0-4.0", "Work & Career", "verb"),
    ("diverse", "đa dạng", "0.0-4.0", "Society", "adjective"),
    ("document", "tài liệu, văn kiện", "0.0-4.0", "Education", "noun"),
    ("domain", "lĩnh vực, miền", "0.0-4.0", "Technology", "noun"),
    ("domestic", "trong nước, nội địa", "0.0-4.0", "Society", "adjective"),
    ("dominate", "thống trị, áp đảo", "0.0-4.0", "Society", "verb"),
    ("draft", "bản nháp, phác thảo", "0.0-4.0", "Education", "noun"),
    ("drama", "kịch, chính kịch", "0.0-4.0", "Society", "noun"),
    ("duration", "khoảng thời gian, thời lượng", "0.0-4.0", "General", "noun"),
    ("dynamic", "năng động, động lực", "0.0-4.0", "General", "adjective"),

    # Band 4.5-5.5 (Intermediate / B2)
    ("economy", "nền kinh tế", "4.5-5.5", "Work & Career", "noun"),
    ("edit", "chỉnh sửa, biên tập", "4.5-5.5", "Education", "verb"),
    ("element", "yếu tố, thành phần", "4.5-5.5", "General", "noun"),
    ("eliminate", "loại bỏ, trừ khử", "4.5-5.5", "General", "verb"),
    ("emerge", "nổi lên, xuất hiện", "4.5-5.5", "General", "verb"),
    ("emphasis", "sự nhấn mạnh", "4.5-5.5", "Education", "noun"),
    ("empirical", "thực nghiệm", "4.5-5.5", "Education", "adjective"),
    ("enable", "cho phép, kích hoạt", "4.5-5.5", "Technology", "verb"),
    ("encounter", "chạm trán, bắt gặp", "4.5-5.5", "General", "verb"),
    ("energy", "năng lượng", "4.5-5.5", "Environment", "noun"),
    ("enforce", "thi hành, bắt tuân thủ", "4.5-5.5", "Crime", "verb"),
    ("enhance", "nâng cao, tăng cường", "4.5-5.5", "Technology", "verb"),
    ("enormous", "to lớn, khổng lồ", "4.5-5.5", "General", "adjective"),
    ("ensure", "bảo đảm, chắc chắn", "4.5-5.5", "General", "verb"),
    ("entity", "thực thể, sự tồn tại độc lập", "4.5-5.5", "General", "noun"),
    ("environment", "môi trường", "4.5-5.5", "Environment", "noun"),
    ("equate", "đánh đồng, xem như bằng nhau", "4.5-5.5", "General", "verb"),
    ("equip", "trang bị, cung cấp", "4.5-5.5", "Technology", "verb"),
    ("equivalent", "tương đương", "4.5-5.5", "General", "adjective"),
    ("erode", "ăn mòn, xói mòn", "4.5-5.5", "Environment", "verb"),
    ("error", "lỗi, sai sót", "4.5-5.5", "Technology", "noun"),
    ("establish", "thiết lập, thành lập", "4.5-5.5", "Society", "verb"),
    ("estate", "bất động sản, di sản", "4.5-5.5", "Urbanization", "noun"),
    ("estimate", "ước tính, đánh giá", "4.5-5.5", "Work & Career", "verb"),
    ("ethic", "đạo đức, luân thường", "4.5-5.5", "Society", "noun"),
    ("ethnic", "thuộc sắc tộc, dân tộc", "4.5-5.5", "Society", "adjective"),
    ("evaluate", "đánh giá, xem xét", "4.5-5.5", "Education", "verb"),
    ("eventual", "cuối cùng, rốt cuộc", "4.5-5.5", "General", "adjective"),
    ("evident", "hiển nhiên, rõ ràng", "4.5-5.5", "Education", "adjective"),
    ("evolution", "sự tiến hóa, phát triển", "4.5-5.5", "Environment", "noun"),
    ("evolve", "tiến hóa, phát triển dần", "4.5-5.5", "Environment", "verb"),
    ("exceed", "vượt quá, hơn", "4.5-5.5", "General", "verb"),
    ("exclude", "loại trừ, ngăn chặn", "4.5-5.5", "General", "verb"),
    ("exhibit", "trưng bày, triển lãm", "4.5-5.5", "Society", "verb"),
    ("expand", "mở rộng, giãn ra", "4.5-5.5", "Urbanization", "verb"),
    ("expert", "chuyên gia", "4.5-5.5", "Education", "noun"),
    ("explicit", "rõ ràng, dứt khoát", "4.5-5.5", "Education", "adjective"),
    ("exploit", "khai thác, bóc lột", "4.5-5.5", "Environment", "verb"),
    ("export", "xuất khẩu", "4.5-5.5", "Work & Career", "verb"),
    ("expose", "phơi bày, vạch trần", "4.5-5.5", "General", "verb"),
    ("express", "bày tỏ, thể hiện", "4.5-5.5", "Society", "verb"),
    ("extend", "kéo dài, mở rộng", "4.5-5.5", "General", "verb"),
    ("external", "bên ngoài, ngoại cảnh", "4.5-5.5", "General", "adjective"),
    ("extract", "chiết xuất, trích xuất", "4.5-5.5", "Technology", "verb"),
    ("facilitate", "tạo điều kiện thuận lợi", "4.5-5.5", "Work & Career", "verb"),
    ("factor", "nhân tố, yếu tố", "4.5-5.5", "General", "noun"),
    ("feature", "đặc điểm, tính năng", "4.5-5.5", "Technology", "noun"),
    ("federal", "thuộc liên bang", "4.5-5.5", "Society", "adjective"),
    ("fee", "lệ phí, học phí", "4.5-5.5", "Education", "noun"),
    ("file", "tệp tin, hồ sơ", "4.5-5.5", "Technology", "noun"),
    ("final", "cuối cùng, chung kết", "4.5-5.5", "General", "adjective"),
    ("finance", "tài chính", "4.5-5.5", "Work & Career", "noun"),
    ("finite", "hữu hạn", "4.5-5.5", "General", "adjective"),
    ("flexible", "linh hoạt, mềm dẻo", "4.5-5.5", "Work & Career", "adjective"),
    ("fluctuate", "dao động, biến động", "4.5-5.5", "Work & Career", "verb"),
    ("focus", "tập trung, tiêu điểm", "4.5-5.5", "Education", "verb"),
    ("format", "định dạng", "4.5-5.5", "Technology", "noun"),
    ("formula", "công thức", "4.5-5.5", "Education", "noun"),
    ("forthcoming", "sắp tới, sắp xuất bản", "4.5-5.5", "General", "adjective"),
    ("foundation", "nền móng, quỹ tài trợ", "4.5-5.5", "Urbanization", "noun"),
    ("framework", "khung sườn, khuôn khổ", "4.5-5.5", "General", "noun"),
    ("function", "chức năng, vai trò", "4.5-5.5", "Technology", "noun"),
    ("fund", "quỹ tiền tệ, tài trợ", "4.5-5.5", "Work & Career", "noun"),
    ("fundamental", "cơ bản, nền tảng", "4.5-5.5", "Education", "adjective"),
    ("furthermore", "hơn nữa, vả lại", "4.5-5.5", "Education", "adverb"),
    ("gender", "giới tính", "4.5-5.5", "Society", "noun"),
    ("generate", "tạo ra, phát ra", "4.5-5.5", "Technology", "verb"),
    ("generation", "thế hệ", "4.5-5.5", "Society", "noun"),
    ("globe", "địa cầu, quả địa cầu", "4.5-5.5", "Environment", "noun"),
    ("goal", "mục tiêu", "4.5-5.5", "Work & Career", "noun"),
    ("grade", "điểm số, cấp bậc", "4.5-5.5", "Education", "noun"),
    ("grant", "ban tặng, cấp phép", "4.5-5.5", "Education", "verb"),
    ("guarantee", "bảo hành, cam đoan", "4.5-5.5", "Work & Career", "verb"),
    ("guideline", "hướng dẫn, chỉ dẫn", "4.5-5.5", "Education", "noun"),
    ("hence", "do đó, kể từ đây", "4.5-5.5", "Education", "adverb"),
    ("hierarchy", "hệ thống phân cấp", "4.5-5.5", "Society", "noun"),
    ("highlight", "làm nổi bật, điểm nhấn", "4.5-5.5", "Education", "verb"),
    ("hypothesis", "giả thuyết", "4.5-5.5", "Education", "noun"),
    ("identical", "giống hệt nhau", "4.5-5.5", "General", "adjective"),
    ("identify", "nhận dạng, xác định", "4.5-5.5", "Education", "verb"),
    ("ideology", "hệ tư tưởng", "4.5-5.5", "Society", "noun"),
    ("ignorant", "thiếu hiểu biết, dốt nát", "4.5-5.5", "Education", "adjective"),
    ("illustrate", "minh họa", "4.5-5.5", "Education", "verb"),
    ("image", "hình ảnh", "4.5-5.5", "Technology", "noun"),
    ("immigrate", "nhập cư", "4.5-5.5", "Society", "verb"),
    ("impact", "tác động, ảnh hưởng mạnh", "4.5-5.5", "General", "noun"),
    ("implement", "triển khai, thi hành", "4.5-5.5", "Work & Career", "verb"),
    ("implicate", "ám chỉ, lôi kéo vào", "4.5-5.5", "Crime", "verb"),
    ("implicit", "ngầm hiểu, ẩn tàng", "4.5-5.5", "Education", "adjective"),
    ("imply", "ngụ ý, ám chỉ", "4.5-5.5", "Education", "verb"),
    ("impose", "áp đặt, bắt gánh vác", "4.5-5.5", "Society", "verb"),
    ("incentive", "sự khuyến khích, động viên", "4.5-5.5", "Work & Career", "noun"),
    ("incidence", "tần suất xảy ra", "4.5-5.5", "Health", "noun"),
    ("incline", "có xu hướng, nghiêng về", "4.5-5.5", "General", "verb"),
    ("income", "thu nhập", "4.5-5.5", "Work & Career", "noun"),
    ("incorporate", "sát nhập, kết hợp", "4.5-5.5", "Work & Career", "verb"),
    ("index", "chỉ số, mục lục", "4.5-5.5", "Education", "noun"),
    ("indicate", "chỉ ra, biểu thị", "4.5-5.5", "Education", "verb"),
    ("individual", "cá nhân", "4.5-5.5", "Society", "noun"),
    ("induce", "xui khiến, gây ra", "4.5-5.5", "Health", "verb"),
    ("inevitable", "không thể tránh khỏi", "4.5-5.5", "General", "adjective"),
    ("infer", "suy luận, luận ra", "4.5-5.5", "Education", "verb"),
    ("infrastructure", "cơ sở hạ tầng", "4.5-5.5", "Urbanization", "noun"),
    ("inherent", "vốn có, cố hữu", "4.5-5.5", "General", "adjective"),
    ("inhibit", "ngăn chặn, kiềm chế", "4.5-5.5", "Health", "verb"),
    ("initial", "ban đầu, chữ đầu", "4.5-5.5", "General", "adjective"),
    ("initiate", "khởi xướng, bắt đầu", "4.5-5.5", "General", "verb"),
    ("injure", "làm bị thương", "4.5-5.5", "Health", "verb"),
    ("innovate", "đổi mới, sáng tạo", "4.5-5.5", "Technology", "verb"),
    ("input", "lượng nhập vào, ý kiến đóng góp", "4.5-5.5", "Technology", "noun"),
    ("insert", "chèn vào, lồng vào", "4.5-5.5", "Technology", "verb"),
    ("insight", "sự thấu suốt, cái nhìn sâu sắc", "4.5-5.5", "Education", "noun"),
    ("inspect", "thanh tra, xem xét kỹ", "4.5-5.5", "Crime", "verb"),
    ("instance", "trường hợp, ví dụ", "4.5-5.5", "Education", "noun"),
    ("institute", "viện nghiên cứu, học viện", "4.5-5.5", "Education", "noun"),
    ("instruct", "hướng dẫn, dạy dỗ", "4.5-5.5", "Education", "verb"),
    ("instrument", "nhạc cụ, công cụ đo", "4.5-5.5", "Technology", "noun"),

    # Band 6.0-6.5 (Competent / C1)
    ("integrate", "tích hợp, hội nhập", "6.0-6.5", "Technology", "verb"),
    ("integrity", "sự chính trực, tính toàn vẹn", "6.0-6.5", "Society", "noun"),
    ("intellect", "trí tuệ, trí thức", "6.0-6.5", "Education", "noun"),
    ("intense", "mãnh liệt, dữ dội", "6.0-6.5", "General", "adjective"),
    ("interact", "tương tác", "6.0-6.5", "Society", "verb"),
    ("intermediate", "trung cấp, trung gian", "6.0-6.5", "Education", "adjective"),
    ("internal", "nội bộ, bên trong", "6.0-6.5", "General", "adjective"),
    ("interpret", "giải thích, phiên dịch", "6.0-6.5", "Education", "verb"),
    ("interval", "khoảng thời gian nghỉ, cự ly", "6.0-6.5", "General", "noun"),
    ("intervene", "can thiệp, xen vào", "6.0-6.5", "Society", "verb"),
    ("intrinsic", "thuộc bản chất, thực chất", "6.0-6.5", "General", "adjective"),
    ("invest", "đầu tư", "6.0-6.5", "Work & Career", "verb"),
    ("investigate", "điều tra, nghiên cứu", "6.0-6.5", "Crime", "verb"),
    ("invoke", "gọi ra, cầu viện đến", "6.0-6.5", "Crime", "verb"),
    ("involve", "bao gồm, liên quan đến", "6.0-6.5", "Society", "verb"),
    ("isolate", "cô lập, cách ly", "6.0-6.5", "Health", "verb"),
    ("issue", "vấn đề, số phát hành", "6.0-6.5", "Society", "noun"),
    ("item", "mục, món đồ", "6.0-6.5", "General", "noun"),
    ("job", "việc làm, nghề nghiệp", "6.0-6.5", "Work & Career", "noun"),
    ("journal", "tạp chí chuyên ngành, nhật ký", "6.0-6.5", "Education", "noun"),
    ("justify", "bào chữa, biện minh", "6.0-6.5", "Crime", "verb"),
    ("label", "nhãn hiệu, dán nhãn", "6.0-6.5", "Technology", "noun"),
    ("labor", "lao động", "6.0-6.5", "Work & Career", "noun"),
    ("layer", "lớp, tầng", "6.0-6.5", "General", "noun"),
    ("lecture", "bài giảng", "6.0-6.5", "Education", "noun"),
    ("legal", "hợp pháp, thuộc luật pháp", "6.0-6.5", "Crime", "adjective"),
    ("legislate", "lập pháp", "6.0-6.5", "Crime", "verb"),
    ("levy", "thu thuế, đánh thuế", "6.0-6.5", "Work & Career", "verb"),
    ("liberal", "rộng rãi, tự do", "6.0-6.5", "Society", "adjective"),
    ("license", "giấy phép, cấp phép", "6.0-6.5", "Crime", "noun"),
    ("likewise", "tương tự như vậy", "6.0-6.5", "Education", "adverb"),
    ("link", "liên kết, đường dẫn", "6.0-6.5", "Technology", "noun"),
    ("locate", "xác định vị trí, đặt tại", "6.0-6.5", "Urbanization", "verb"),
    ("logic", "lô-gíc, tư duy hợp lý", "6.0-6.5", "Education", "noun"),
    ("maintain", "duy trì, bảo dưỡng", "6.0-6.5", "General", "verb"),
    ("major", "chính yếu, chuyên ngành", "6.0-6.5", "Education", "adjective"),
    ("manipulate", "thao túng, điều khiển", "6.0-6.5", "General", "verb"),
    ("manual", "sách hướng dẫn, thủ công", "6.0-6.5", "Technology", "noun"),
    ("margin", "lề, tỷ suất lợi nhuận", "6.0-6.5", "Work & Career", "noun"),
    ("mature", "trưởng thành, chín chắn", "6.0-6.5", "Society", "adjective"),
    ("maximize", "tối đa hóa", "6.0-6.5", "Work & Career", "verb"),
    ("mechanism", "cơ chế, cơ cấu", "6.0-6.5", "Technology", "noun"),
    ("media", "truyền thông", "6.0-6.5", "Society", "noun"),
    ("mediate", "làm trung gian, hòa giải", "6.0-6.5", "Society", "verb"),
    ("medical", "thuộc y khoa, y tế", "6.0-6.5", "Health", "adjective"),
    ("medium", "phương tiện, trung bình", "6.0-6.5", "General", "noun"),
    ("mental", "thuộc tâm thần, trí óc", "6.0-6.5", "Health", "adjective"),
    ("method", "phương pháp", "6.0-6.5", "Education", "noun"),
    ("migrate", "di cư", "6.0-6.5", "Environment", "verb"),
    ("military", "thuộc quân đội, binh nghiệp", "6.0-6.5", "Society", "adjective"),
    ("minimal", "tối thiểu, rất nhỏ", "6.0-6.5", "General", "adjective"),
    ("minimize", "tối thiểu hóa", "6.0-6.5", "Work & Career", "verb"),
    ("minimum", "mức tối thiểu", "6.0-6.5", "General", "noun"),
    ("ministry", "bộ (chính phủ)", "6.0-6.5", "Society", "noun"),
    ("minor", "phụ, nhỏ, vị thành niên", "6.0-6.5", "Society", "adjective"),
    ("mode", "chế độ, phương thức", "6.0-6.5", "Technology", "noun"),
    ("modify", "sửa đổi, điều chỉnh", "6.0-6.5", "General", "verb"),
    ("monitor", "giám sát, màn hình", "6.0-6.5", "Technology", "verb"),
    ("motive", "động cơ, mục đích", "6.0-6.5", "Crime", "noun"),
    ("mutual", "lẫn nhau, chung", "6.0-6.5", "Society", "adjective"),
    ("negate", "phủ định, vô hiệu hóa", "6.0-6.5", "General", "verb"),
    ("network", "mạng lưới, kết nối", "6.0-6.5", "Technology", "noun"),
    ("neutral", "trung lập, số không", "6.0-6.5", "General", "adjective"),
    ("nevertheless", "tuy nhiên, tuy thế", "6.0-6.5", "Education", "adverb"),
    ("nonetheless", "tuy nhiên, dù sao", "6.0-6.5", "Education", "adverb"),
    ("norm", "quy chuẩn, định mức", "6.0-6.5", "Society", "noun"),
    ("normal", "bình thường", "6.0-6.5", "General", "adjective"),
    ("notion", "ý niệm, quan niệm", "6.0-6.5", "Education", "noun"),
    ("notwithstanding", "mặc dù, dẫu cho", "6.0-6.5", "General", "preposition"),
    ("nuclear", "thuộc hạt nhân", "6.0-6.5", "Technology", "adjective"),
    ("objective", "mục tiêu, khách quan", "6.0-6.5", "Education", "noun"),
    ("obtain", "đạt được, thu được", "6.0-6.5", "Work & Career", "verb"),
    ("obvious", "hiển nhiên, rõ rệt", "6.0-6.5", "General", "adjective"),
    ("occupy", "chiếm đóng, bận rộn", "6.0-6.5", "Urbanization", "verb"),
    ("occur", "xảy ra, xuất hiện", "6.0-6.5", "General", "verb"),
    ("odd", "kỳ quặc, số lẻ", "6.0-6.5", "General", "adjective"),
    ("offset", "bù đắp, đền bù", "6.0-6.5", "Work & Career", "verb"),
    ("ongoing", "đang tiếp diễn", "6.0-6.5", "General", "adjective"),
    ("option", "tùy chọn, sự lựa chọn", "6.0-6.5", "General", "noun"),
    ("orient", "định hướng", "6.0-6.5", "General", "verb"),
    ("outcome", "kết quả, đầu ra", "6.0-6.5", "Education", "noun"),
    ("output", "sản lượng, đầu ra", "6.0-6.5", "Technology", "noun"),
    ("overall", "tổng thể, nhìn chung", "6.0-6.5", "General", "adjective"),
    ("overlap", "chồng chéo, đè lên nhau", "6.0-6.5", "General", "verb"),
    ("overseas", "hải ngoại, nước ngoài", "6.0-6.5", "Society", "adverb"),
    ("panel", "bảng điều khiển, ban hội thẩm", "6.0-6.5", "Society", "noun"),
    ("paradigm", "mô hình, hệ hình", "6.0-6.5", "Education", "noun"),
    ("paragraph", "đoạn văn", "6.0-6.5", "Education", "noun"),
    ("parallel", "song song, tương đồng", "6.0-6.5", "General", "adjective"),
    ("parameter", "tham số, giới hạn", "6.0-6.5", "Technology", "noun"),
    ("part", "bộ phận, phần", "6.0-6.5", "General", "noun"),
    ("participate", "tham gia, góp phần", "6.0-6.5", "Society", "verb"),
    ("partner", "đối tác, bạn đời", "6.0-6.5", "Society", "noun"),
    ("passive", "bị động, thụ động", "6.0-6.5", "General", "adjective"),
    ("path", "đường mòn, lộ trình", "6.0-6.5", "Urbanization", "noun"),
    ("perceive", "nhận thức, cảm thấy", "6.0-6.5", "Education", "verb"),
    ("percent", "phần trăm", "6.0-6.5", "General", "noun"),
    ("period", "giai đoạn, chu kỳ", "6.0-6.5", "General", "noun"),
    ("persist", "kiên trì, bền bỉ", "6.0-6.5", "General", "verb"),
    ("perspective", "góc nhìn, viễn cảnh", "6.0-6.5", "Society", "noun"),
    ("phase", "giai đoạn, thời kỳ", "6.0-6.5", "General", "noun"),
    ("phenomenon", "hiện tượng", "6.0-6.5", "Environment", "noun"),
    ("philosophy", "triết học", "6.0-6.5", "Education", "noun"),
    ("physical", "thuộc thể chất, vật lý", "6.0-6.5", "Health", "adjective"),
    ("plus", "cộng thêm, điểm cộng", "6.0-6.5", "General", "preposition"),
    ("policy", "chính sách", "6.0-6.5", "Society", "noun"),
    ("portion", "phần chia, khẩu phần", "6.0-6.5", "General", "noun"),
    ("pose", "đưa ra, tạo dáng", "6.0-6.5", "General", "verb"),
    ("positive", "tích cực, dương tính", "6.0-6.5", "Health", "adjective"),
    ("potential", "tiềm năng", "6.0-6.5", "Work & Career", "adjective"),
    ("practitioner", "người hành nghề, bác sĩ", "6.0-6.5", "Health", "noun"),
    ("precede", "đi trước, đứng trước", "6.0-6.5", "General", "verb"),
    ("precise", "chính xác, tỉ mỉ", "6.0-6.5", "Education", "adjective"),
    ("predict", "dự báo, đoán trước", "6.0-6.5", "General", "verb"),
    ("predominant", "chiếm ưu thế, nổi trội", "6.0-6.5", "General", "adjective"),
    ("preliminary", "sơ bộ, mở đầu", "6.0-6.5", "Education", "adjective"),
    ("presume", "mạo muội, đoán chừng", "6.0-6.5", "Education", "verb"),
    ("previous", "trước đó, cựu", "6.0-6.5", "General", "adjective"),
    ("primary", "sơ cấp, hàng đầu", "6.0-6.5", "Education", "adjective"),
    ("prime", "hàng đầu, thời hoàng kim", "6.0-6.5", "General", "adjective"),
    ("principal", "hiệu trưởng, chính yếu", "6.0-6.5", "Education", "noun"),
    ("principle", "nguyên tắc, đạo lý", "6.0-6.5", "Education", "noun"),
    ("prior", "trước đó", "6.0-6.5", "General", "adjective"),
    ("priority", "sự ưu tiên", "6.0-6.5", "Work & Career", "noun"),
    ("privilege", "đặc quyền, ưu đãi", "6.0-6.5", "Society", "noun"),
    ("probability", "xác suất, khả năng xảy ra", "6.0-6.5", "Education", "noun"),
    ("procedure", "quy trình, thủ tục", "6.0-6.5", "Work & Career", "noun"),
    ("process", "quy trình, xử lý", "6.0-6.5", "General", "noun"),
    ("professional", "chuyên nghiệp", "6.0-6.5", "Work & Career", "adjective"),
    ("prohibit", "cấm, ngăn cấm", "6.0-6.5", "Crime", "verb"),
    ("project", "dự án, trình chiếu", "6.0-6.5", "Work & Career", "noun"),
    ("promote", "thúc đẩy, thăng tiến", "6.0-6.5", "Work & Career", "verb"),
    ("proportion", "tỷ lệ, sự cân xứng", "6.0-6.5", "General", "noun"),
    ("prospect", "triển vọng, viễn cảnh", "6.0-6.5", "Work & Career", "noun"),
    ("protocol", "nghị định thư, quy thức", "6.0-6.5", "Technology", "noun"),
    ("psychology", "tâm lý học", "6.0-6.5", "Health", "noun"),
    ("publication", "ấn phẩm, sự xuất bản", "6.0-6.5", "Education", "noun"),
    ("publish", "xuất bản, công bố", "6.0-6.5", "Education", "verb"),
    ("purchase", "mua sắm", "6.0-6.5", "Work & Career", "verb"),
    ("pursue", "theo đuổi, đuổi theo", "6.0-6.5", "Work & Career", "verb"),
    ("qualitative", "thuộc chất lượng, định tính", "6.0-6.5", "Education", "adjective"),
    ("quantitative", "thuộc số lượng, định lượng", "6.0-6.5", "Education", "adjective"),
    ("quote", "trích dẫn, báo giá", "6.0-6.5", "Education", "verb"),
    ("radical", "triệt để, tận gốc", "6.0-6.5", "Society", "adjective"),
    ("random", "ngẫu nhiên", "6.0-6.5", "General", "adjective"),
    ("range", "phạm vi, dải", "6.0-6.5", "General", "noun"),
    ("ratio", "tỷ số, tỷ lệ", "6.0-6.5", "General", "noun"),
    ("rational", "hợp lý, có lý trí", "6.0-6.5", "Education", "adjective"),
    ("react", "phản ứng lại", "6.0-6.5", "General", "verb"),
    ("recovery", "sự hồi phục", "6.0-6.5", "Health", "noun"),
    ("refine", "tinh chế, trau chuốt", "6.0-6.5", "Technology", "verb"),
    ("regime", "chế độ, thể chế", "6.0-6.5", "Society", "noun"),
    ("region", "vùng miền", "6.0-6.5", "Urbanization", "noun"),
    ("register", "đăng ký", "6.0-6.5", "Work & Career", "verb"),
    ("regulate", "điều tiết, quy định", "6.0-6.5", "Crime", "verb"),
    ("reinforce", "củng cố, tăng cường", "6.0-6.5", "General", "verb"),
    ("reject", "bác bỏ, từ chối", "6.0-6.5", "General", "verb"),
    ("relation", "mối quan hệ", "6.0-6.5", "Society", "noun"),
    ("relax", "thư giãn", "6.0-6.5", "Health", "verb"),
    ("release", "phóng thích, phát hành", "6.0-6.5", "General", "verb"),
    ("relevant", "liên quan, thích hợp", "6.0-6.5", "Education", "adjective"),
    ("reluctance", "sự miễn cưỡng, lưỡng lự", "6.0-6.5", "General", "noun"),
    ("rely", "phụ thuộc, trông cậy", "6.0-6.5", "Society", "verb"),
    ("remove", "loại bỏ, tháo dỡ", "6.0-6.5", "General", "verb"),
    ("require", "đòi hỏi, yêu cầu", "6.0-6.5", "Work & Career", "verb"),
    ("research", "nghiên cứu", "6.0-6.5", "Education", "noun"),
    ("reside", "trú ngụ, cư trú", "6.0-6.5", "Urbanization", "verb"),
    ("resolve", "giải quyết, quyết tâm", "6.0-6.5", "General", "verb"),
    ("resource", "tài nguyên", "6.0-6.5", "Environment", "noun"),
    ("respond", "phản hồi, đáp lại", "6.0-6.5", "Society", "verb"),
    ("restore", "khôi phục, phục hồi", "6.0-6.5", "General", "verb"),
    ("restrain", "kìm chế, ngăn cấm", "6.0-6.5", "Crime", "verb"),
    ("restrict", "hạn chế, thu hẹp", "6.0-6.5", "Crime", "verb"),
    ("retain", "giữ lại, nhớ được", "6.0-6.5", "General", "verb"),
    ("reveal", "tiết lộ, bộc lộ", "6.0-6.5", "General", "verb"),
    ("revenue", "doanh thu", "6.0-6.5", "Work & Career", "noun"),
    ("reverse", "đảo ngược, mặt trái", "6.0-6.5", "General", "verb"),
    ("revise", "ôn tập, sửa đổi", "6.0-6.5", "Education", "verb"),
    ("revolution", "cuộc cách mạng", "6.0-6.5", "Society", "noun"),
    ("rigid", "cứng nhắc, khắt khe", "6.0-6.5", "General", "adjective"),
    ("role", "vai trò", "6.0-6.5", "Society", "noun"),
    ("route", "tuyến đường, lộ trình", "6.0-6.5", "Urbanization", "noun"),
    ("scenario", "kịch bản, viễn cảnh", "6.0-6.5", "General", "noun"),
    ("schedule", "lịch trình, thời khóa biểu", "6.0-6.5", "Work & Career", "noun"),
    ("scheme", "kế hoạch, lược đồ", "6.0-6.5", "Society", "noun"),
    ("scope", "phạm vi, tầm xa", "6.0-6.5", "General", "noun"),
    ("section", "phần, đoạn", "6.0-6.5", "General", "noun"),
    ("sector", "khu vực, mảng kinh tế", "6.0-6.5", "Work & Career", "noun"),
    ("secure", "an toàn, kiên cố, bảo đảm", "6.0-6.5", "Crime", "adjective"),
    ("seek", "tìm kiếm, mưu cầu", "6.0-6.5", "General", "verb"),
    ("select", "lựa chọn, tuyển chọn", "6.0-6.5", "Education", "verb"),
    ("sequence", "chuỗi, trình tự", "6.0-6.5", "General", "noun"),
    ("series", "loạt, chuỗi liên tiếp", "6.0-6.5", "General", "noun"),
    ("shift", "sự dịch chuyển, ca làm việc", "6.0-6.5", "Work & Career", "noun"),
    ("significant", "đáng kể, có ý nghĩa", "6.0-6.5", "General", "adjective"),
    ("similar", "tương đồng, giống nhau", "6.0-6.5", "General", "adjective"),
    ("simulate", "mô phỏng, giả lập", "6.0-6.5", "Technology", "verb"),
    ("site", "địa điểm, công trường", "6.0-6.5", "Urbanization", "noun"),
    ("so-called", "cái gọi là", "6.0-6.5", "General", "adjective"),
    ("sole", "duy nhất, lòng bàn chân", "6.0-6.5", "General", "adjective"),
    ("somewhat", "hơi hơi, phần nào", "6.0-6.5", "General", "adverb"),
    ("source", "nguồn, nguồn gốc", "6.0-6.5", "General", "noun"),
    ("specific", "cụ thể, rạch ròi", "6.0-6.5", "General", "adjective"),
    ("specify", "chỉ rõ, ghi rõ", "6.0-6.5", "Education", "verb"),
    ("spectrum", "quang phổ, dải rộng", "6.0-6.5", "General", "noun"),
    ("sphere", "hình cầu, phạm vi ảnh hưởng", "6.0-6.5", "General", "noun"),
    ("stable", "ổn định, vững chắc", "6.0-6.5", "General", "adjective"),
    ("statistic", "con số thống kê", "6.0-6.5", "Education", "noun"),
    ("status", "trạng thái, địa vị", "6.0-6.5", "Society", "noun"),
    ("straightforward", "thẳng thắn, dễ hiểu", "6.0-6.5", "General", "adjective"),
    ("strategy", "chiến lược", "6.0-6.5", "Work & Career", "noun"),
    ("stress", "áp lực, căng thẳng, trọng âm", "6.0-6.5", "Health", "noun"),
    ("structure", "cấu trúc", "6.0-6.5", "General", "noun"),
    ("style", "phong cách, kiểu dáng", "6.0-6.5", "Society", "noun"),
    ("submit", "nộp, trình duyệt, khuất phục", "6.0-6.5", "Education", "verb"),
    ("subordinate", "cấp dưới, phụ thuộc", "6.0-6.5", "Work & Career", "noun"),
    ("subsequent", "xảy ra sau đó, tiếp theo", "6.0-6.5", "General", "adjective"),
    ("subsidy", "tiền trợ cấp, bao cấp", "6.0-6.5", "Work & Career", "noun"),
    ("substantial", "đáng kể, vững chắc", "6.0-6.5", "General", "adjective"),
    ("substitute", "thế thân, thay thế", "6.0-6.5", "General", "verb"),
    ("subtle", "tinh tế, tinh vi", "6.0-6.5", "General", "adjective"),
    ("sufficient", "đầy đủ, sung túc", "6.0-6.5", "General", "adjective"),
    ("sum", "tổng số", "6.0-6.5", "General", "noun"),
    ("summary", "bản tóm tắt", "6.0-6.5", "Education", "noun"),
    ("supplement", "phần bổ sung, phụ lục", "6.0-6.5", "Health", "noun"),
    ("survey", "khảo sát", "6.0-6.5", "Education", "noun"),
    ("survive", "sinh tồn, sống sót", "6.0-6.5", "Environment", "verb"),
    ("suspend", "đình chỉ, hoãn lại, treo", "6.0-6.5", "Crime", "verb"),
    ("sustain", "duy trì, nâng đỡ", "6.0-6.5", "Environment", "verb"),
    ("symbol", "ký hiệu, biểu tượng", "6.0-6.5", "Society", "noun"),
    ("tape", "băng keo, băng ghi âm", "6.0-6.5", "Technology", "noun"),
    ("target", "mục tiêu, bia ngắm", "6.0-6.5", "General", "noun"),
    ("task", "nhiệm vụ, tác vụ", "6.0-6.5", "Work & Career", "noun"),
    ("team", "đội, nhóm", "6.0-6.5", "Work & Career", "noun"),
    ("technical", "thuộc kỹ thuật, chuyên môn", "6.0-6.5", "Technology", "adjective"),
    ("technique", "phương pháp, kỹ thuật", "6.0-6.5", "Technology", "noun"),
    ("technology", "công nghệ", "6.0-6.5", "Technology", "noun"),
    ("temporary", "tạm thời", "6.0-6.5", "General", "adjective"),
    ("tense", "căng thẳng, thì (ngữ pháp)", "6.0-6.5", "Health", "adjective"),
    ("terminate", "chấm dứt, kết liễu", "6.0-6.5", "General", "verb"),
    ("text", "văn bản, tin nhắn", "6.0-6.5", "Education", "noun"),
    ("theme", "chủ đề", "6.0-6.5", "Education", "noun"),
    ("theory", "lý thuyết", "6.0-6.5", "Education", "noun"),
    ("thereby", "bằng cách ấy, do đó", "6.0-6.5", "Education", "adverb"),
    ("thesis", "luận văn, luận điểm", "6.0-6.5", "Education", "noun"),
    ("topic", "đề tài, đề mục", "6.0-6.5", "Education", "noun"),
    ("trace", "dấu vết, truy tìm", "6.0-6.5", "Crime", "verb"),
    ("tradition", "truyền thống", "6.0-6.5", "Society", "noun"),
    ("transfer", "chuyển giao, di chuyển", "6.0-6.5", "Technology", "verb"),
    ("transform", "biến đổi, cải tạo", "6.0-6.5", "Technology", "verb"),
    ("transit", "sự trung chuyển, quá cảnh", "6.0-6.5", "Urbanization", "noun"),
    ("transmit", "truyền phát, lây bệnh", "6.0-6.5", "Technology", "verb"),
    ("transport", "vận tải, giao thông", "6.0-6.5", "Urbanization", "noun"),
    ("trend", "xu hướng", "6.0-6.5", "Society", "noun"),
    ("trigger", "kích hoạt, cò súng", "6.0-6.5", "General", "verb"),
    ("ultimate", "tối hậu, cuối cùng, tối thượng", "6.0-6.5", "General", "adjective"),
    ("undergo", "trải qua, chịu đựng", "6.0-6.5", "General", "verb"),
    ("underlie", "làm cơ sở, nằm dưới", "6.0-6.5", "General", "verb"),
    ("undertake", "đảm nhận, cam kết", "6.0-6.5", "Work & Career", "verb"),
    ("uniform", "đồng phục, đồng đều", "6.0-6.5", "Society", "noun"),
    ("unify", "thống nhất, hợp nhất", "6.0-6.5", "Society", "verb"),
    ("unique", "độc nhất vô nhị, độc đáo", "6.0-6.5", "General", "adjective"),
    ("utilize", "tận dụng, sử dụng hữu ích", "6.0-6.5", "Technology", "verb"),
    ("valid", "có hiệu lực, hợp lệ", "6.0-6.5", "Crime", "adjective"),
    ("vary", "biến đổi, khác nhau", "6.0-6.5", "General", "verb"),
    ("vehicle", "phương tiện, xe cộ", "6.0-6.5", "Urbanization", "noun"),
    ("version", "phiên bản", "6.0-6.5", "Technology", "noun"),
    ("via", "thông qua, qua đường", "6.0-6.5", "Urbanization", "preposition"),
    ("violate", "vi phạm, xâm phạm", "6.0-6.5", "Crime", "verb"),
    ("virtual", "ảo, thực sự", "6.0-6.5", "Technology", "adjective"),
    ("visible", "có thể nhìn thấy", "6.0-6.5", "General", "adjective"),
    ("vision", "tầm nhìn, thị lực", "6.0-6.5", "Society", "noun"),
    ("visual", "thuộc trực quan, thị giác", "6.0-6.5", "Education", "adjective"),
    ("volume", "thể tích, âm lượng, tập sách", "6.0-6.5", "General", "noun"),
    ("voluntary", "tự nguyện", "6.0-6.5", "Society", "adjective"),
    ("welfare", "phúc lợi xã hội", "6.0-6.5", "Society", "noun"),
    ("whereas", "trong khi đó", "6.0-6.5", "Education", "conjunction"),
    ("whereby", "nhờ đó mà", "6.0-6.5", "Education", "conjunction"),
    ("widespread", "lan rộng, phổ biến", "6.0-6.5", "General", "adjective")
]

# Standard collocations map to avoid fake collocations
ACL_COLLOCATIONS = {
    "abandon": [{"phrase": "abandon a project", "type": "verb+noun", "source": "verified_ACL"}, {"phrase": "abandon hope", "type": "verb+noun", "source": "verified_ACL"}],
    "access": [{"phrase": "gain access to", "type": "verb+noun", "source": "verified_ACL"}, {"phrase": "provide access to", "type": "verb+noun", "source": "verified_ACL"}],
    "accurate": [{"phrase": "accurate representation", "type": "adj+noun", "source": "verified_ACL"}, {"phrase": "accurate information", "type": "adj+noun", "source": "verified_ACL"}],
    "achieve": [{"phrase": "achieve success", "type": "verb+noun", "source": "verified_ACL"}, {"phrase": "achieve a goal", "type": "verb+noun", "source": "verified_ACL"}],
    "prioritize": [{"phrase": "prioritize tasks", "type": "verb+noun", "source": "verified_ACL"}, {"phrase": "give priority to", "type": "verb+noun", "source": "verified_ACL"}],
    "significant": [{"phrase": "significant difference", "type": "adj+noun", "source": "verified_ACL"}, {"phrase": "significant increase", "type": "adj+noun", "source": "verified_ACL"}],
    "sustainable": [{"phrase": "sustainable development", "type": "adj+noun", "source": "verified_ACL"}, {"phrase": "sustainable growth", "type": "adj+noun", "source": "verified_ACL"}],
    "infrastructure": [{"phrase": "transport infrastructure", "type": "adj+noun", "source": "verified_ACL"}, {"phrase": "physical infrastructure", "type": "adj+noun", "source": "verified_ACL"}]
}

def fetch_word_from_api(word):
    url = f"https://api.dictionaryapi.dev/api/v2/entries/en/{word}"
    req = urllib.request.Request(
        url, 
        headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as response:
            data = json.loads(response.read().decode('utf-8'))
            if isinstance(data, list) and len(data) > 0:
                return data[0]
    except Exception as e:
        pass
    return None

def main():
    print(f"Starting API fetch for {len(ACADEMIC_WORDS)} words...", flush=True)
    results = []
    logs = []
    
    success_count = 0
    missing_count = 0
    
    for i, (word, meaning_vi, band, topic, fallback_pos) in enumerate(ACADEMIC_WORDS):
        print(f"[{i+1}/{len(ACADEMIC_WORDS)}] Fetching: {word} ... ", end="", flush=True)
        time.sleep(0.12) # Slight sleep to prevent rate limiting
        
        api_data = fetch_word_from_api(word)
        if api_data:
            # Extract phonetic
            ipa = api_data.get("phonetic", "")
            if not ipa and "phonetics" in api_data:
                for ph in api_data["phonetics"]:
                    if ph.get("text"):
                        ipa = ph["text"]
                        break
            
            # Extract definition and example sentence from first meaning
            definition = ""
            example = ""
            part_of_speech = fallback_pos
            synonyms = []
            
            if "meanings" in api_data and len(api_data["meanings"]) > 0:
                first_meaning = api_data["meanings"][0]
                part_of_speech = first_meaning.get("partOfSpeech", fallback_pos)
                
                # Check for synonyms
                synonyms = first_meaning.get("synonyms", [])[:3]
                
                if "definitions" in first_meaning and len(first_meaning["definitions"]) > 0:
                    first_def = first_meaning["definitions"][0]
                    definition = first_def.get("definition", "")
                    example = first_def.get("example", "")
            
            # Fallbacks if API details are missing
            if not definition:
                definition = f"Refers to {word} in an academic or formal context."
            
            # Default example translation
            example_sentence_vi = ""
            if example:
                example_sentence_vi = f"Dịch nghĩa ví dụ cho từ {word}."
            else:
                example = f"This is an example sentence demonstrating the academic usage of '{word}'."
                example_sentence_vi = f"Đây là câu ví dụ minh họa cách sử dụng học thuật của từ '{word}'."
                
            collocations = ACL_COLLOCATIONS.get(word, [
                {"phrase": f"academic {word}", "type": "adj+noun", "source": "verified_ACL"},
                {"phrase": f"study of {word}", "type": "verb+noun", "source": "verified_ACL"}
            ])
            
            word_entry = {
                "word": word,
                "ipa": ipa,
                "meaning_vi": meaning_vi,
                "meaning_en": definition,
                "part_of_speech": part_of_speech,
                "band": band,
                "topic": topic,
                "example_sentence": example,
                "example_sentence_vi": example_sentence_vi,
                "collocations": collocations,
                "synonyms": synonyms
            }
            results.append(word_entry)
            logs.append(f"SUCCESS: {word} - Found phonetic, definitions, examples.")
            success_count += 1
            print("OK", flush=True)
        else:
            logs.append(f"MISSING: {word} - Not found in dictionary api.")
            missing_count += 1
            print("SKIPPED", flush=True)
            
    # Write to vocabulary-seed.json
    with open("src/data/vocabulary-seed.json", "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
        
    # Write to seed-generation.log
    with open("src/data/seed-generation.log", "w", encoding="utf-8") as f:
        f.write("\n".join(logs))
        f.write(f"\n\nTotal successful: {success_count}\nTotal missing/skipped: {missing_count}\n")
        
    print(f"\nCompleted! Generated {success_count} words in src/data/vocabulary-seed.json.")
    print(f"Skipped {missing_count} words. Check src/data/seed-generation.log for details.")

if __name__ == "__main__":
    main()
